export const GET_POPULARITY_RANKING = 'GET_POPULARITY_RANKING';
export const GET_TOP_RATED_MOVIE = 'GET_TOP_RATED_MOVIE';
export const GET_ACTION_MOVIE = 'GET_ACTION_MOVIE';
export const GET_COMEDY_MOVIE = 'GET_COMEDY_MOVIE';
export const GET_HORROR_MOVIE = 'GET_HORROR_MOVIE';
export const GET_ROMANCE_MOVIE = 'GET_ROMANCE_MOVIE';
export const GET_DOCUMENT_MOVIE = 'GET_DOCUMENT_MOVIE';
export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES';
export const GET_TRENDING_MOVIE = 'GET_TRENDING_MOVIE';

export const SET_MOVIE_DETAIL = 'SET_MOVIE_DETAIL';
